# Generated by Django 3.1.3 on 2020-12-03 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CarBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specification', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
                ('body_number', models.IntegerField(default=0)),
                ('engine_number', models.IntegerField(default=0)),
                ('graduation_year', models.CharField(max_length=20)),
                ('run', models.IntegerField(default=0)),
                ('car_prise', models.IntegerField(default=0)),
                ('rent_price', models.IntegerField(default=0)),
                ('last_maintenance_date', models.CharField(max_length=20)),
                ('special_sign', models.CharField(max_length=100)),
                ('car_bran_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.carbrands')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=13)),
                ('passport_data', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=13)),
                ('passport_data', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Occupations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_name', models.CharField(max_length=50)),
                ('salary', models.IntegerField(default=0)),
                ('responsibility', models.CharField(max_length=100)),
                ('requirement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.CharField(max_length=20)),
                ('term_of_rent', models.CharField(max_length=10)),
                ('return_date', models.CharField(max_length=10)),
                ('rent_prise', models.IntegerField(default=0)),
                ('payment_mark', models.CharField(max_length=10)),
                ('additional_services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.additionalservices')),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.cars')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.clients')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.employees')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='occupation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.occupations'),
        ),
        migrations.AddField(
            model_name='cars',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.employees'),
        ),
    ]
